import { Briefcase, Building2 } from "lucide-react";
import { SectionHeading } from "./SectionHeading";

const highlights = [
  "Developed and optimized 50+ RESTful APIs for the Spacio platform — rental management, invoicing, payments, grievance handling, and reporting — improving response performance and system stability.",
  "Architected backend workflows for patient survey collection, questionnaire routing, and healthcare analytics for Smart ER, enabling faster data processing and accurate survey insights.",
  "Integrated React frontends with Django REST APIs, reducing communication issues and improving page load responsiveness by ~30%.",
  "Implemented Celery + RabbitMQ asynchronous pipelines for the high-traffic QSync queue-management system, increasing throughput and eliminating processing delays at peak load.",
  "Automated full-stack data migration from MongoDB to PostgreSQL with Python scripts and cron-based scheduled syncs, reducing manual work and discrepancies by 90%.",
  "Built a dynamic quotation and budgeting engine for Felsomat robotic-machinery proposals, improving proposal delivery time by 40% through autogenerated costing reports.",
  "Engineered secure Django REST APIs for Hero pathology specimen tracking — chain-of-custody logging, audit trails, and automated status updates.",
  "Designed a centralized digital visitor entry-pass system serving multiple IT-park offices, improving access-control efficiency and reducing manual verification time.",
  "Collaborated across cross-functional Agile teams (frontend, QA, design, product) to deliver scalable features within sprint timelines while maintaining code quality and documentation standards.",
];

export function Experience() {
  return (
    <section id="experience" className="relative py-24 md:py-32">
      <div className="mx-auto max-w-6xl px-4">
        <SectionHeading
          kicker="03 — Experience"
          title="Shipping production backends at scale."
          subtitle="Software Engineer at Pearlsoft Technologies, building real systems used every day."
        />

        <div className="mt-12 grid gap-8 md:grid-cols-3">
          {/* Sticky job card */}
          <div className="md:col-span-1">
            <div className="sticky top-28 rounded-2xl border border-border bg-surface/60 p-6">
              <div className="flex items-center gap-3">
                <div className="grid h-11 w-11 place-items-center rounded-lg bg-primary/10 text-primary ring-1 ring-primary/20">
                  <Building2 className="h-5 w-5" />
                </div>
                <div>
                  <div className="font-display text-lg font-semibold leading-tight">
                    Pearlsoft Technologies
                  </div>
                  <div className="text-xs text-muted-foreground">Kerala, India</div>
                </div>
              </div>

              <div className="mt-5 flex items-center gap-2 text-sm">
                <Briefcase className="h-4 w-4 text-primary" />
                <span className="font-medium">Software Engineer</span>
              </div>
              <div className="mt-1 font-mono text-xs text-muted-foreground">
                Sep 2022 — Aug 2025
              </div>

              <ul className="mt-5 flex flex-wrap gap-2">
                {["Django", "DRF", "FastAPI", "Celery", "RabbitMQ", "PostgreSQL", "MongoDB", "React", "Docker"].map(
                  (t) => (
                    <li
                      key={t}
                      className="rounded-md border border-border bg-background/60 px-2 py-0.5 font-mono text-[11px] text-muted-foreground"
                    >
                      {t}
                    </li>
                  )
                )}
              </ul>
            </div>
          </div>

          {/* Timeline highlights */}
          <div className="md:col-span-2">
            <ol className="relative space-y-5 border-l border-border pl-6">
              {highlights.map((h, i) => (
                <li
                  key={i}
                  className="group relative animate-fade-up opacity-0"
                  style={{ animationDelay: `${i * 70}ms`, animationFillMode: "forwards" }}
                >
                  <span className="absolute -left-[31px] top-1.5 grid h-4 w-4 place-items-center rounded-full border border-primary/40 bg-background">
                    <span className="h-1.5 w-1.5 rounded-full bg-primary transition-all group-hover:scale-150 group-hover:shadow-[0_0_12px_var(--primary)]" />
                  </span>
                  <p className="text-pretty text-muted-foreground leading-relaxed">{h}</p>
                </li>
              ))}
            </ol>
          </div>
        </div>
      </div>
    </section>
  );
}
