import { ArrowUpRight, Github } from "lucide-react";
import { SectionHeading } from "./SectionHeading";

const projects = [
  {
    title: "Spacio — Rental Management Platform",
    description:
      "Developed 50+ RESTful APIs powering rental management, invoicing, payments, grievance handling, and reporting modules. Improved response performance and overall system stability.",
    tags: ["Django", "DRF", "PostgreSQL", "REST", "React"],
    accent: "from-primary/30 to-accent/20",
  },
  {
    title: "Smart ER — Healthcare Survey & Analytics",
    description:
      "Architected backend workflows for patient survey collection, questionnaire routing, and healthcare analytics — enabling faster data processing and more accurate survey insights.",
    tags: ["Django", "DRF", "PostgreSQL", "JWT"],
    accent: "from-accent/30 to-primary/20",
  },
  {
    title: "QSync — Queue Management System",
    description:
      "High-traffic queue platform with Celery + RabbitMQ asynchronous pipelines. Increased request throughput and eliminated processing delays during peak load.",
    tags: ["FastAPI", "Celery", "RabbitMQ", "Redis", "Docker"],
    accent: "from-[oklch(0.7_0.15_300)]/30 to-primary/20",
  },
  {
    title: "Felsomat — Quotation & Budgeting Engine",
    description:
      "Dynamic quotation and budgeting engine for robotic-machinery proposals. Autogenerated costing reports improved proposal delivery time by 40%.",
    tags: ["Django", "Python", "PostgreSQL", "PDF"],
    accent: "from-primary/30 to-[oklch(0.7_0.15_300)]/20",
  },
  {
    title: "Hero — Pathology Specimen Tracking",
    description:
      "Secure Django REST APIs for chain-of-custody logging, audit trails, and automated status updates for pathology specimen tracking.",
    tags: ["Django", "DRF", "RBAC", "PostgreSQL"],
    accent: "from-accent/30 to-primary/20",
  },
  {
    title: "Digital Visitor Entry-Pass System",
    description:
      "Centralized visitor entry-pass system serving multiple IT-park offices. Improved access-control efficiency and dramatically reduced manual verification time.",
    tags: ["Django", "DRF", "MySQL", "OAuth 2.0"],
    accent: "from-primary/30 to-accent/20",
  },
];

export function Projects() {
  return (
    <section id="projects" className="relative py-24 md:py-32">
      <div className="mx-auto max-w-6xl px-4">
        <SectionHeading
          kicker="04 — Selected work"
          title="Products I've shipped."
          subtitle="Real backend systems delivered at Pearlsoft Technologies (2022 – 2025)."
        />

        <div className="mt-12 grid gap-6 md:grid-cols-2">
          {projects.map((p) => (
            <article
              key={p.title}
              className="group relative overflow-hidden rounded-2xl border border-border bg-surface/60 p-7 transition-all duration-300 hover:-translate-y-1 hover:border-primary/40"
            >
              <div
                className={`absolute -right-20 -top-20 h-48 w-48 rounded-full bg-gradient-to-br ${p.accent} opacity-40 blur-3xl transition-all duration-500 group-hover:opacity-70`}
              />
              <div className="relative">
                <div className="flex items-start justify-between gap-4">
                  <h3 className="font-display text-xl font-semibold tracking-tight md:text-2xl">
                    {p.title}
                  </h3>
                  <div className="flex shrink-0 gap-2">
                    <button
                      aria-label="GitHub"
                      className="grid h-9 w-9 place-items-center rounded-lg border border-border bg-background/50 text-muted-foreground transition-all hover:border-primary/40 hover:text-primary"
                    >
                      <Github className="h-4 w-4" />
                    </button>
                    <button
                      aria-label="Open"
                      className="grid h-9 w-9 place-items-center rounded-lg border border-border bg-background/50 text-muted-foreground transition-all group-hover:rotate-45 hover:border-primary/40 hover:text-primary"
                    >
                      <ArrowUpRight className="h-4 w-4" />
                    </button>
                  </div>
                </div>
                <p className="mt-3 text-pretty text-muted-foreground">{p.description}</p>
                <ul className="mt-5 flex flex-wrap gap-2">
                  {p.tags.map((t) => (
                    <li
                      key={t}
                      className="rounded-md border border-border bg-background/60 px-2.5 py-1 font-mono text-xs text-muted-foreground"
                    >
                      {t}
                    </li>
                  ))}
                </ul>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
